### ISSUE TITLE
[general] Use of TypeScript as in return types

### ISSUE THREAD

**Issue by peebeejay** [aave/aave-protocol#14]
Hey guys - i've been poking around the repo & was curious when I saw the high use of TypeScript (which I use professionally). 

Was generally wondering why there's such a high use of `as` when returning values in a few functions - it can definitely result in type errors that typescript won't catch? case in point is the line referenced below. 

https://github.com/aave/aave-protocol/blob/99c7e4e2ec6636d7bc71494a37253b8a2d3c2179/thegraph/raw/initializers.ts#L32

**Comment by kyzia551** [comment]
The problem here that it's not TypeScript, but AssemblyScript, which are acts a bit differently, without such code it was impossible to compile.
