### ISSUE TITLE
[Question] Are there any migration/deployment script ?

### ISSUE THREAD

**Issue by EdsonAlcala** [aave/aave-protocol#15]
Hello, I'm trying to deploy the aave-protocol from scratch for learning purposes but I'm not able to find any migrations or deployment scripts. 

Is there any resource out there where I can check this? This is for a Remix plugin to allow users to deploy aave protocol easily.

Thanks

**Comment by cryptoman04** [comment]
@EdsonAlcala were you able to figure this out? I am actually trying to figure this out as well for learning purposes too.

**Comment by Ayid7676** [comment]
@EdsonAlcala were you able to figure this out? I am actually trying to figure this out as well for learning purposes too.

**Comment by Ayid7676** [comment]
Hello, I'm trying to deploy the aave-protocol from scratch for learning purposes but I'm not able to find any migrations or deployment scripts.

Is there any resource out there where I can check this? This is for a Remix plugin to allow users to deploy aave protocol easily.

Thanks
