### ISSUE TITLE
Listing of Crypto.com

### ISSUE THREAD

**Issue by andrealiuu** [aave/aave-protocol#26]
Hi Aave team,  

This is Andrea from Crypto.com and I hope your team is doing all well under the backdrop of COVID-19.

I am responsible for outreach on behalf of Crypto.com and I am outreaching to you because I have found there would be potential opportunities to deepen the relationship between Crypto.com and the Aave team.  

Crypto.com was founded in 2016 with the mission to accelerate the world's transition to cryptocurrency. Crypto.com is always actively building relationships with different token partners and one of the initiatives was launching the token price pages project where we create profile pages to promote different crypto projects. For instance, we have also created a dedicated page for Aave to show the latest market pulse and price movement with token information and an official website, we generate traffic and visibility for our partners with our effort on SEO, and our partners will get free publicity with our pages. You can find this page at https://crypto.com/price/aave and feel free to give us any comments to improve the page.

Apart from the above initiative, Aave is also deeply integrated with Crypto.com products. First of all, Aave is one of the 70+ cryptocurrencies that can be bought from Crypto.com App.Aave is also one of the supported tokens that can be traded on Crypto.com Exchange and swap through Crypto.com DeFi Swap.

I just came across the Aave website and I have found the page https://aave.com/ecosystem for showcasing merchants and services which currently accepts Aave. I am wondering if it is possible to add our company logo with links directing to https://crypto.com/  under the section as an honor for our long lasting working relationship?

No pressure at all for our pitch and we are looking forward to hearing from you soon. 

Thank you for your time and consideration!

Cheers,
Andrea

**Comment by kyzia551** [comment]
Hey @andrealiuu!
Sorry, it's not the right place for such proposals plz contact us via email/discord/telegram/etc
