### ISSUE TITLE
Long Term DNS 

### ISSUE THREAD

**Issue by michael-spengler** [aave/aave-protocol#33]
Hi Aave Team.

First of all: Thank you for what you do. I appreciate aave.com very much.

Now to my recommendation: I propose you to consider one of the following options:
1. https://unstoppabledomains.com/
2. https://ens.domains/

or perhaps even both. 

Background: I'd like to support you in making sure that aave is about to stay. Feedback = welcome.

Thanks for checking this
Michael

**Comment by kyzia551** [comment]
Hey @michael-spengler!
Sorry, but it's not the right place for such proposals, plz contact us via email/discord/telegram/etc
