### ISSUE TITLE
Integrating a Fiat On-Ramp & Off-Ramp

### ISSUE THREAD

**Issue by michael-spengler** [aave/aave-protocol#34]
Hi Aave Team.

Could this be an inspiration to integrate a Peer 2 Peer Fiat On-Ramp & Off-Ramp to Aave:
https://www.youtube.com/watch?v=ZVZgxPvmlpA ?

Kind regards
Michael

**Comment by kyzia551** [comment]
Sorry @michael-spengler, but it's not the right place for such proposals, plz contact us via email/discord/telegram
