### ISSUE TITLE
Aave V2 Subgraph?

### ISSUE THREAD

**Issue by watersnake1** [aave/aave-protocol#40]
It looks like the subgraph on theGraph's explorer is for version 1 of Aave's protocol. Where can I find the version 2 subgraph?

**Comment by Decentralisedme** [comment]
Hi Water, I found this :
- https://thegraph.com/explorer/subgraph/aave/protocol-v2
- https://gitlab.com/aave-tech/dlp/token-migration-subgraph: it is gitlab and page no found

I hope it helps, but I still have problems with V1 (issues/39)

**Comment by kyzia551** [comment]
Hi guys!

We're still finalizing subgaph for v2, but we will publish it next week. It will be in a separate repo, will publish the URL in this issue, stay tuned

**Comment by kyzia551** [comment]
It's published https://github.com/aave/protocol-v2-subgraph
