### ISSUE TITLE
[thegraph][feature request] average rates over time

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-protocol#5]
While the rate displayed on aave.com is kinda nice, rates on aave are quite volatile.
As a user it would be interesting to know what's the average rate for a certain asset over the last 24h or 1month.

**Comment by kyzia551** [comment]
Hey @sakulstra !

I don't think that it's doable on TheGraph level, because of their specific protocol organization, but we plan to make an API with such data

**Comment by sakulstra** [comment]
@kyzia551 good to hear that :+1:
For the meantime do you have a suggestion on how to calculate that rate manually?

I'm currently thinking about calculating all the rates based on utilization within a given timeframe to be able to calculate a properly weighted average, but that somehow seems overly complicated.

**Comment by kyzia551** [comment]
Will be introduced as weighted average on our API in next 1 week

**Comment by sakulstra** [comment]
hayho, any updadte on this? i'm monitoring this repo an while there wasn't any commit in thegraph there obviously were some updates - couldn't find this specific one though.

**Comment by sakulstra** [comment]
closing this as it wont be part of the gql api as it can't be, but might be on another public api soon :eye:
