### ISSUE TITLE
[thegraph][feature request] fees & lend burn

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-protocol#6]
As side-product of aave beeing utilized, lend is burned. As this is part of the protocol, I guess it should also be part of the aave graph.

What I think would be interesting (and doable by my understanding of what is possible with the graph)

**totalBurnedLendByProtocol**
As i get thegraph docs it's not possible to just monitor incoming transactions on a given address(so we cannot just monitor 0x0 for incoming lend)?, but it should be possible to monitor token burns initiated by the protocol and sum them up.

**feesYetToBeCollected**
Should be doable by summing up the fees to be collected by borrows() and subtracting the fees payed in repays()

**totalCollectedFees**
Should be doable by summing up the repayed fees and fees from the flashLoans

**availableFees**
Should be doable by totalCollectedFees - fees used to burn lend

**Comment by kyzia551** [comment]
Outdated, this data was added already
