### ISSUE TITLE
Getting an error inputting asset in FlashLoan.sol

### ISSUE THREAD

**Issue by aamazie** [aave/aave-protocol#82]
I'm following this tutorial loosely (by loosely I'm not using the Kovan network because I'm having issues with that as well, I'm testing on both the JavaScript VM (London) and Web3 Provider Mainnet Fork with HardHat): https://www.quicknode.com/guides/defi/how-to-make-a-flash-loan-using-aave

All the files are compiled fine. However, when I go to submit an asset like the Ethereum contract address "0x74b23882a30290451A17c44f4F05243b6b58C76d" in the flashloan() function, I get a "Transaction reverted without a reason string" Error. The address that deployed the contract already has a lot of test ETH in it so I'm not sure what could be the issue.

And just a sidenote why I'm not using Kovan like the tutorial, all the good faucets are down and the one that works only let me get like .0031 KETH for the day which was enough for one deployment and when the contract deployed it failed for some reason and ate all the Kovan ETH along with it. This failure may have been due to the fact that I had to adjust the gas price down just slightly to meet the amount I had, but I doubt it, I'm not really sure why it failed on the Injected Web3 and that worries me for future real deployments. Any insight into any of this would be super appreciated. Thanks!

**Comment by kkk324** [comment]
Same here.
and https://testnet.aave.com/faucet failed.

**Comment by aamazie** [comment]
Just an update. I was able to do everything the tutoria says on Kovan, I'm just running into the error when I input the DAI asset 0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD like it says in the tutorial. I'm closing this issue because I opened a new version with #86
