### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by cedcec** [aave/aave-protocol#9]
Hello Team,

Cloud you please update your docs at least regarding the flashloans?
https://developers.aave.com/?typescript#implementing-a-flashloanreceiver-contract

The solidity example is not working anymore since openzeppelin changed their github directory structure (import is not working), also they moved to solidity 0.6.0.

NetworkMetadataProvider.sol file dissapeared  from the github repository.

And so on.

Thanks!

**Comment by mrdavey** [comment]
Thanks for letting us know. We'll have an update to the docs released soon (ETA before end of week).
